const ActionTypes = {
  UPDATE_LOADING: 'UPDATE_LOADING',
  GET_ITEMS: 'GET_ITEMS',
  GET_ITEMS_SUCCESS: 'GET_ITEMS_SUCCESS',
  GET_ITEMS_FAILURE: 'GET_ITEMS_FAILURE',
  ADD_ITEM: 'ADD_ITEM',
  UPDATE_ITEM: 'UPDATE_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  ITEMS_FILTER_CHANGE: 'ITEMS_FILTER_CHANGE',
  CLEAR_ITEMS_LIST: 'CLEAR_ITEMS_LIST',
  CLEAR_DONE_ITEMS: 'CLEAR_DONE_ITEMS'
}

export default ActionTypes
